8.1 1-я часть
htmlacademy-javascript/1247093-keksobooking-22 pull request #10
Opened 2021-03-02 18:35 UTC by Serafima93

2021-03-04 05:21 UTC, 4err requested changes

2021-03-04 05:21 UTC, 4err commented on js/map.js
> +  setHouseType(renderSimilarList(adverts));
Тут нужно передавать функцию, чтобы она использовалась внутри `setHouseType`. А ты передаешь вызов функции. 
Должно быть что-то вроде: `setHouseType(renderSimilarList);`

2021-03-04 05:21 UTC, 4err commented on js/map.js
> +    cb();
А где непосредственно фильттрация то? Вот тут нужно фильтровать массив карточек и отфильтрованный передать в cb();

2021-03-10 05:51 UTC, 4err requested changes

2021-03-10 05:51 UTC, 4err commented on js/map.js
> +const ANY = 'any';
Константы должны идти до основного кода.

2021-03-10 05:51 UTC, 4err commented on js/map.js
> +const getUrl = 'https://22.javascript.pages.academy/keksobooking/data';
Это тоже константа

2021-03-10 05:51 UTC, 4err commented on js/map.js
> +  }).filter((ad) => {
Это все еще цепочка фильтров. 
Нужно реализовать проверку внутри одного блока `filter`. 
Посмотри ту демку, что я скидывал тебе.

2021-03-10 05:51 UTC, 4err commented on js/map.js
> +  ));
Очень много однотипного кода. Учитывая, что мы проверяем всегда все фильтры, имеет смысл создать всего одну функцию и повесить ее на форму, отлавливать событие изменения формы и запускать фильтр. Таким образом мы избавимся от кучи повторов и лишних событий.

2021-03-11 12:54 UTC, Serafima93 commented on js/map.js
> +const ANY = 'any';
сделала

2021-03-11 12:54 UTC, Serafima93 commented on js/map.js
> +const getUrl = 'https://22.javascript.pages.academy/keksobooking/data';
сделала

2021-03-11 12:54 UTC, Serafima93 commented on js/map.js
> +  }).filter((ad) => {
сделала

2021-03-11 12:55 UTC, Serafima93 commented on js/map.js
> +  ));
сделала на _.debounce, но я не стала делать все единой функцией, так я путаюсь гораздо больше и я поняла что по ТЗ лучше много мелких функций, чем одна большая

2021-03-11 15:34 UTC, Serafima93 commented on js/map.js
> +  ));
// если вы имелии ввиду что надо вообще удалять функции для каждого поля (надеюсь что нет!!!!)
    // у меня цикл работает только на первый элемент массива. Почему так?

2021-03-11 18:22 UTC, Serafima93 commented
'use strict'

/* global L:readonly */
/* global _:readonly */

import { createPopup } from './card.js';
import { getData } from './api.js';

const ANY = 'any';
const SIMILAR_ADVERT_COUNT = 10;
const RERENDER_DELAY = 500;
const ZOOM = 12;
const LAT = 35.65;
const LNG = 139.78;
const MAIN_ICON_DATA = {
  iconUrl: 'img/main-pin.svg',
  iconSize: [52, 52],
  iconAnchor: [26, 52],
};

const USAUAL_ICON_DATA = {
  iconUrl: 'img/pin.svg',
  iconSize: [40, 40],
  iconAnchor: [20, 40],
};

const COMMA_NUMBER = 5;

const priceValues = {
  START: 10000,
  FINAL: 50000,
};

const mapFilters = document.querySelector('.map__filters');
const housingType = mapFilters.querySelector('#housing-type');
const housingRooms = mapFilters.querySelector('#housing-rooms');
const housingGuests = mapFilters.querySelector('#housing-guests');
const housingPrice = mapFilters.querySelector('#housing-price');
// const housingFeatures = mapFilters.querySelector('#housing-features');
const selectFilters = document.querySelectorAll('.map__filters select');


const getUrl = 'https://22.javascript.pages.academy/keksobooking/data';
const adressCordinate = document.querySelector('#address');

// находим форму и добавляем неактивность
const userForm = document.querySelector('.ad-form');
const fieldsetForm = userForm.querySelectorAll('fieldset');
// находим форму карты и добавляем неактивность.
const mapFilter = document.querySelector('.map__filters');
const mapIcons = mapFilter.querySelector('fieldset');
const mapForms = mapFilter.querySelectorAll('select');



const makeFormDisabled = function () {
  userForm.classList.add('ad-form--disabled');
  fieldsetForm.forEach((value) => {
    value.setAttribute('disabled', 'disabled');
  });
  mapFilter.classList.add('ad-form--disabled');
  mapIcons.setAttribute('disabled', 'disabled');
  mapForms.forEach((value) => {
    value.setAttribute('disabled', 'disabled');
  });

};

makeFormDisabled();

const makeFormActive = function () {
  userForm.classList.remove('ad-form--disabled');
  fieldsetForm.forEach((value) => {
    value.removeAttribute('disabled', 'disabled');
  });

  mapFilter.classList.remove('ad-form--disabled');
  mapIcons.removeAttribute('disabled', 'disabled');
  mapForms.forEach((value) => {
    value.removeAttribute('disabled', 'disabled');
  });
};




// работа с картой

const map = L.map('map')
  .on('load', () => {
    //Карта инициализирована. Возвращение атрибутов

    makeFormActive();

  })
  .setView([LAT, LNG], ZOOM);

L.tileLayer(
  'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  },
).addTo(map);


const mainPinIcon = L.icon({
  iconUrl: MAIN_ICON_DATA.iconUrl,
  iconSize: MAIN_ICON_DATA.iconSize,
  iconAnchor: MAIN_ICON_DATA.iconAnchor,
});

const marker = L.marker(
  {
    lat: LAT,
    lng: LNG,
  },
  {
    draggable: true,
    icon: mainPinIcon,
  },
);
marker.addTo(map);


// создаем группу слоев - пока пустую
const pins = L.layerGroup([]);
pins // добавляем его на карту
  .addTo(map);


const createFeaturesArray = function () {
  const housingFeaturesChecked = mapFilters.querySelectorAll('.map__features input[name="features"]:checked');
  const checkedFeatures = Array.from(housingFeaturesChecked);
  const featuresCheckedArray = [];
  for (let i = 0; i <= checkedFeatures.length - 1; i++) {
    const ad = checkedFeatures[i].value;
    featuresCheckedArray.push(ad);
  }
  return featuresCheckedArray
};



// const setHouseType = (cb) => {
//   housingType.addEventListener('change', (evt) => {
//     evt.target.value = housingType.value;
//     pins.clearLayers();

//     cb();
//   });
// };

// const setRoomsCount = (cb) => {
//   housingRooms.addEventListener('change', (evt) => {
//     evt.target.value = housingRooms.value;
//     pins.clearLayers();

//     cb();
//   });
// };

// const setGuestsCount = (cb) => {
//   housingGuests.addEventListener('change', (evt) => {
//     evt.target.value = housingGuests.value;
//     pins.clearLayers();

//     cb();
//   });
// };

// const setPriceCount = (cb) => {
//   housingPrice.addEventListener('change', (evt) => {
//     evt.target.value = housingPrice.value;
//     pins.clearLayers();

//     cb();
//   });
// };

// const setFeatures = (cb) => {

//   housingFeatures.addEventListener('change', () => {

//     pins.clearLayers();
//     cb();
//   });
// };




const setFeatures2 = (cb) => {
  selectFilters.forEach(function (elem) {
    elem.addEventListener('change', function (evt) {
      elem.value = evt.target.value;
      pins.clearLayers();
      cb();
    });
  });
};



const renderSimilarList = (adverts) => {

  const filterAdData = function (el) {
    let isType = true;
    let isPrice = true;
    let isGuest = true;
    let isRooms = true;
    let isFeature = true;
    const priceLimit = {
      middle: el.offer.price >= priceValues.START && el.offer.price <= priceValues.FINAL,
      low: el.offer.price < priceValues.START,
      high: el.offer.price >= priceValues.FINAL,
    };
    const checkedList = createFeaturesArray(); // получаем массив выделеных фичей

    for (let i = 0; i < selectFilters.length; i++) {
      if (selectFilters[i] === housingType) {
        if (selectFilters[i].value !== ANY) { isType = el.offer.type === selectFilters[i].value; }
      }
      if (selectFilters[i] === housingRooms) {
        if (selectFilters[i].value !== ANY && el.offer.rooms.toString() !== selectFilters[i].value) {
          return isRooms = false
        }
      }
      if (selectFilters[i] === housingGuests) {
        if (selectFilters[i].value !== ANY && el.offer.guests.toString() !== selectFilters[i].value) {
          return isGuest = false
        }
      }
      if (housingPrice.value !== ANY) {
        isPrice = el.offer.price === priceLimit[housingPrice.value];
        isPrice = priceLimit[housingPrice.value];
      }
      if (checkedList.length > 0) {
        let i = 0;
        while (isFeature && i < checkedList.length) {
          isFeature = el.offer.features.includes(checkedList[i]);
          i++;
        }
      }
    }
    return isType && isRooms && isGuest && isFeature && isPrice
  };




  // если вы имелии ввиду что надо вообще удалять функции для каждого поля (надеюсь что нет!!!!)
  //  я даже это сделала, но блин правильно ли?

  //   if (housingType.value !== ANY) {
  //     isType = el.offer.type === housingType.value;
  //   }
  //   if (housingRooms.value !== ANY) {
  //     isRooms = el.offer.rooms.toString() === housingRooms.value;
  //   }
  //   if (housingGuests.value !== ANY) {
  //     isGuest = el.offer.guests.toString() === housingGuests.value;
  //   }
  //   if (housingPrice.value !== ANY) {
  //     isPrice = el.offer.price === priceLimit[housingPrice.value];
  //     isPrice = priceLimit[housingPrice.value];
  //   }
  //   if (housingGuests.value !== ANY) {
  //     isGuest = el.offer.guests.toString() === housingGuests.value;
  //   }
  //   if (checkedList.length > 0) {
  //     let i = 0;
  //     while (isFeature && i < checkedList.length) {
  //       isFeature = el.offer.features.includes(checkedList[i]);
  //       i++;
  //     }
  //   }
  //   return isType && isRooms && isGuest && isFeature && isPrice
  // };

  // проверка

  let ads = adverts.filter(filterAdData);

  // console.log(ads);
  ads
    .slice(0, SIMILAR_ADVERT_COUNT)
    .forEach((offer) => {

      const iconUsual = L.icon({
        iconUrl: USAUAL_ICON_DATA.iconUrl,
        iconSize: USAUAL_ICON_DATA.iconSize,
        iconAnchor: USAUAL_ICON_DATA.iconAnchor,
      });

      const marker2 = L.marker(
        {
          lat: offer.location.lat,
          lng: offer.location.lng,
        },
        {
          iconUsual,
        },
      );

      marker2.bindPopup(
        createPopup(offer),
      );

      pins.addLayer(marker2);
    });
};



getData(getUrl, (adverts) => {
  renderSimilarList(adverts);

  let setFiter = _. [...]

2021-03-12 05:41 UTC, 4err requested changes

2021-03-12 05:41 UTC, 4err commented on js/map.js
> +  });
Теперь ты делаешь тоже самое, только в цикле. Я имел ввиду повесить обработчик на саму форму: тег `form`. Когда у любого элемента формы сработает событие `change` оно же сработает и у формы.

2021-03-12 05:41 UTC, 4err commented on js/map.js
> +      if (selectFilters[i] === housingType) {
Вот тут тоже вместо этой кучи if лучше использовать `switch/case`.

2021-03-12 09:19 UTC, Serafima93 commented on js/map.js
> +      if (selectFilters[i] === housingType) {
я выбрала другой стиль фильтров как у тебя в демке сейчас, там ифы по другому выглядят, и по мне органичнее сейчас. Со свитчом, будет куча ретернов, и код короче не стал.

2021-03-12 09:32 UTC, merged