Функции. Второе задание
htmlacademy-javascript/1247093-keksobooking-22 pull request #2
Opened 2021-01-30 17:45 UTC by Serafima93

2021-01-31 05:09 UTC, 4err requested changes

2021-01-31 05:09 UTC, 4err commented on js/main.js
> +    return 'Максимум не может быть меньше минимума!';
Старайся минимизировать количество `return` в функциях. Старайся писать код так, чтобы был всего один `return` иначе это запутывает код. 
В данной ситуации можно завести переменную и записывать в нее ошибку. Если ошибок нет, записывать в нее результат вычислений. И в самом конце в return возвращать эту переменную. В идеале нам нужно собрать и показать пользователю все ошибки, котоорые он допустил сразу. При таком подходе ему не придется перебирать варианты ввода, чтобы понять, а что он делает не так.

2021-01-31 05:09 UTC, 4err commented on js/main.js
> +let numberComma
Все что относится к функции должно быть внутри функции.

2021-01-31 05:09 UTC, 4err commented on js/main.js
> +const getRandomArbitrary = function (min, max) {
По условию задачи, 3 параметр функции это количество знаков после запятой. 
Тебе не нужно считать количество знаков, тебе нужно округлить число до этого количества знаков. 
https://learn.javascript.ru/number#netochnye-vychisleniya
Вот этот блок должен помочь в решении задачи.

2021-01-31 05:09 UTC, 4err commented on js/main.js
> +  return randomNumber + ' рандомальный номер и его колличество знаков после запятой - ' + numberComma
В качестве ответа функция должна возвращать просто число.

2021-01-31 08:19 UTC, Serafima93 commented on index.html
> +  <script src="../1247093-keksobooking-22/js/main.js"></script>
убрала

2021-02-01 05:47 UTC, 4err requested changes

2021-02-01 05:47 UTC, 4err commented on index.html
> +  <script src="../js/main.js"></script>
А теперь он вообще не подключен. Тебе не нужно подниматься на уровень вверх с помощью `../`. 
Просто `js/main.js`

2021-02-01 05:47 UTC, 4err commented on js/main.js
> +  return result
Уже лучше, но все еще 2 `return`. 

Не забывай, что ты можешь комбинировать условия используя логически операторы  **И** `&&` и **ИЛИ** `||`
Таким образом, если у тебя одно сообщение, то можно это записать в одно условие, которое и выставит флаг ошибки. Для наличия ошибки лучше использовать булевый тип данных: true и false. По умолчанию, мы всегда считаем, что ошибок нет, поэтому переменная должна иметь на старте значение **false**, а в условии уже перезаписываться на **true**. Тогда не нужно будет делать этих действий с присваиванием **result** значений.

И вот в условии 
```
 if (mistake) {
```
Уже следует прописать else. Это 2 пути развития событий. Именно в этих путях ты назначаешь переменной result какое-то значение. И потом уже в самом конце делаешь `return result` за пределами этого условия.

2021-02-01 05:47 UTC, 4err commented on js/main.js
> +  }
Обрати внимание, что у тебя полностью повторяются проверки для обеих функций. Это называется дублированием кода и в данном случае можно создать третью функцию, которая будет отвечать только за валидацию данных. Мы передаем в нее min и max, она возвращает true/false в зависимости от того, есть ошибки или нет.

2021-02-01 05:47 UTC, 4err commented on js/main.js
> +/* По мне этот вариант красивее
Это пока. Как правило обработка подобных состояний заключается не в просто выводе текста. И соответственно, чем больше условий и проверок, тем запутаннее становится код. Правило хорошего тона иметь в функции один вход и один выход.

2021-02-01 10:29 UTC, Serafima93 commented on index.html
> +  <script src="../js/main.js"></script>
поменяла

2021-02-01 11:42 UTC, merged