Module5 task1
htmlacademy-javascript/1247093-keksobooking-22 pull request #5
Opened 2021-02-13 21:00 UTC by Serafima93

2021-02-14 19:52 UTC, 4err requested changes
https://take.ms/qunxa Нужно чтобы отображались соответствующие иконки, а не текст фич

2021-02-14 19:52 UTC, 4err commented on index.html
> +      <div class="map__canvas" id="map-canvas" style="display: flex;"></div>
У нас единовременно отрисовывается только одна карточка, так что в этом нет необходимости. 

> 3. Отрисуйте один, например первый, из сгенерированных DOM-элементов в блок .map-canvas, чтобы проверить, что данные в разметку были вставлены корректно.

Ну и по хорошему ты должна работать с той разметкой и стилизацией, которую тебе предоставил верстальщик. Сейчас ты не должна вмешиваться в стилизацию.

2021-02-14 19:52 UTC, 4err commented on js/card.js
> +  if (offer.offer.title === undefined) {
Ты можешь в условии использовать отрицание: `if (!offer.offer.title)`
Куча условий это нормально. Можно создать объект-правило и пройтись по всем правилам в цикле и убирать соответствующие элементы, если их не существует, но такой вариант вполне достаточен.

2021-02-14 19:52 UTC, 4err commented on js/card.js
> +    cardElement.querySelector('.popup__title').classList.remove('.popup__title');
Ты удаляешь класс элемента, а нужно убирать элемент полностью.

2021-02-14 19:52 UTC, 4err commented on js/card.js
> +  let ParentElemet = cardElement.querySelector('.popup__photos').children
С Заглавной буквы именуются Классы и перечисления.

2021-02-14 19:52 UTC, 4err commented on js/card.js
> +  // НЕ уверена что поняла правильно этот кусок, ибо тут фаф иконка и как то генерировать картинка+ текст странно
У тебя все картинки уже есть в разметке, по сути тебе нужно удалить элементы, которых нет в твоем оффере. Второй вариант через создание элементов воссоздать разметку с иконками.

2021-02-14 19:52 UTC, 4err commented on js/card.js
> +  cardElement.querySelector('.popup__text--address').textContent = offer.offer.address.x + ' это X ' + offer.offer.address.y + ' это Y';
Используй возможности шаблонных строк. Здесь и далее.

2021-02-14 19:52 UTC, 4err commented on js/data.js
> +const SIMILAR_ADVERT_COUNT = 5;
Задание не менялось, все еще 10.

2021-02-14 19:52 UTC, 4err commented on js/card.js
> +    cardElement.querySelector('.popup__avatar').classList.remove('.popup__avatar');
Ты несколько раз делаешь одни и те же querySelector. Сначала в заполнении, потом тут. Это ресурсозатратная операция, если тебе элемент нужен несколько раз, то лучше присвоить результат поиска переменной и использовать ее.

2021-02-14 19:52 UTC, 4err commented on js/card.js
> +similarCards.forEach((offer) => {
Нужно написать функцию, которая отрисует одну карточку, которую ей передали в качестве параметра.

2021-02-15 11:09 UTC, Serafima93 commented on index.html
> +      <div class="map__canvas" id="map-canvas" style="display: flex;"></div>
убрала

2021-02-15 11:11 UTC, Serafima93 commented on js/card.js
> +  if (offer.offer.title === undefined) {
аа ну значит сохраним)

2021-02-15 11:13 UTC, Serafima93 commented on js/card.js
> +  let ParentElemet = cardElement.querySelector('.popup__photos').children
убрала

2021-02-15 11:17 UTC, Serafima93 commented on js/card.js
> +    cardElement.querySelector('.popup__title').classList.remove('.popup__title');
сделала

2021-02-15 11:23 UTC, Serafima93 commented on js/card.js
> +  cardElement.querySelector('.popup__text--address').textContent = offer.offer.address.x + ' это X ' + offer.offer.address.y + ' это Y';
сделала

2021-02-15 11:39 UTC, Serafima93 commented on js/card.js
> +    cardElement.querySelector('.popup__avatar').classList.remove('.popup__avatar');
сдела

2021-02-15 11:41 UTC, Serafima93 commented on js/data.js
> +const SIMILAR_ADVERT_COUNT = 5;
вернула

2021-02-15 12:29 UTC, Serafima93 commented on js/card.js
> +similarCards.forEach((offer) => {
вроде сделала

2021-02-16 05:50 UTC, 4err requested changes

2021-02-16 05:50 UTC, 4err commented on js/card.js
> +similarCards.forEach((offer) => {
Не, ты все еще в цикле выводишь все карточки. Нужна прям отдельная функция, в которую передаешь данные и они отрисовываются. 
Например: `renderCard(offer)`
И результат этой функции рисует карточку.

2021-02-16 05:50 UTC, 4err commented on js/card.js
> +const randomCard = new Array(1).fill(null).map(() => createAdvert());
заново генерировать не нужно, нужно использовать данные созданные в data.js

2021-02-16 05:50 UTC, 4err commented on js/card.js
> +  if (offer.offer.title === undefined) {
Условия все же лучше переделать на `if (!offer.offer.title)`

2021-02-16 05:50 UTC, 4err commented on js/card.js
> +    titlePopup.classList.remove();
Ты все еще удаляешь класс, а не элемент. Для проверки, попробуй в data.js при генерации удалить разные поля.

2021-02-16 05:50 UTC, 4err commented on js/card.js
> +    newElement.classList.add('popup__feature--'+ad); //добавляем ему класс первый
Используй возможности шаблонных строк. Ну и можно через одну команду add задать несколько классов через запятую.

2021-02-16 05:50 UTC, 4err commented on js/card.js
> +  let titlePopup = cardElement.querySelector('.popup__title');
Здесь и далее все querySelectorы это const же. Ты их не переопределяешь.

2021-02-16 05:50 UTC, 4err commented on js/data.js
> +const PROPERTYTYPE = {
Несколько слов пишутся через нижнее подчеркивание, а не слитно.

2021-02-16 10:44 UTC, Serafima93 commented on js/card.js
> +    titlePopup.classList.remove();
Я убрала classList

2021-02-16 10:52 UTC, Serafima93 commented on js/card.js
> +    newElement.classList.add('popup__feature--'+ad); //добавляем ему класс первый
Шаблонные строки сделала, но вот слить в один add не получается

2021-02-16 10:55 UTC, Serafima93 commented on js/card.js
> +  let titlePopup = cardElement.querySelector('.popup__title');
Все что касается частей поп-апа я переименовала, но вот внутри оставила let я из там меняю-могу менять

2021-02-16 10:55 UTC, Serafima93 commented on js/data.js
> +const PROPERTYTYPE = {
исправила

2021-02-18 04:56 UTC, merged